web: gunicorn mysite.wsgi --log-file -
After your evidence review, I found some errors like this:

1) Incorrect use of TOBE verb

She have 19 years old(incorrect)

There friends may(incorrect)

Where are your mother from? (incorrect)

2) Incorrect use of there is/are

There board a chair(incorrect)

There desk four students(incorrect)

there pencil a notebook(incorrect)

there ruler a big windows(incorrect)

If you want to master these basics concepts please study materials again! then fix it and send me back.

Fernando Temoche

Pretty much better isn't it? Please keep moving to other activities.

Fernando Temoche

I noticed some common errors using the verb LIKE in affirmative, negative or interrogative form
Please study materials then fix it and send me back.
Check your errors:
=========================
========================
Fernando Temoche

After review I noticed, You did this activity incorrect because:
1) Here you must write (6) sentences about sports and animals, describing why you like or dislike it
For example:
I like rabbits because they are cute animals.
Study this example and the write you 6 correct and complete sentences.
Fernando Temoche
