# Generated by Django 3.0 on 2020-03-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_contrato_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='responsable',
        ),
        migrations.AddField(
            model_name='contrato',
            name='print',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
